apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      serviceAccountName: django-service-account
      containers:
      - name: django
        image: hmsacr.azurecr.io/scaleops-demo-django:latest
        ports:
        - containerPort: 8000
        env:
        # Sensitive values from Kubernetes Secrets
        - name: RDS_USERNAME
          value: ltscale
        - name: RDS_PASSWORD
          value: "uzma@1000"
        - name: RDS_ENDPOINT
          value: mysql-service
        - name: RDS_PORT
          value: "3306"
        - name: RDS_DB_NAME
          value: django
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1024Mi"
            cpu: "1000m"